name: lrec-wikipron
channels:
 - conda-forge
 - defaults
 - pytorch
dependencies:
 - baumwelch=0.3.0
 - ngram=1.3.8
 - openfst=1.7.5
 - pynini=2.0.9.post2
 - python=3.6.9
 - pytorch=1.2.0
 - pip=19.3.1
 - numpy=1.17.3
 - openfst=1.7.5
 - pip:
   - fairseq==0.8.0
