#!/bin/bash
# Basic description of the preparation pipeline.

set -eou pipefail

readonly SEED=1169

# Directory of this file
readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for TSV in *.tsv; do
    echo "Shortening: ${TSV}"
    TMP=$(mktemp -t)
    ${DIR}/short.py "${TSV}" > "${TMP}"
    mv "${TMP}" "${TSV}"
done

# Eliminate cases of multiple gold targets for a source.
for TSV in *.tsv; do
    echo "Removing free variation: ${TSV}"
    TMP=$(mktemp -t)
    ./free_variation.py "${TSV}" > "${TMP}"
    mv "${TMP}" "${TSV}"
done


# At this point I manually inspected the most extreme elements.

for TSV in *.tsv; do
    echo "Splitting: ${TSV}"
    BASE=$(basename "${TSV}" .tsv)
    ${DIR}/split.py                      \
        --seed="${SEED}"                 \
        --input_path="${TSV}"            \
        --train_path="${BASE}_train.tsv" \
        --dev_path="${BASE}_dev.tsv"     \
        --test_path="${BASE}_test.tsv"
done
